---
- hosts: Destinationserver
  become: true
  tasks:
  - name: Copy file from machine to machine2
    copy:
     src: /var/lib/jenkins/workspace/new/webapp/target/webapp/index.jsp
     dest: /tmp
 - name: Copy file from machine1 to machine2
    copy:
     src: Text.txt
     dest: /tmp
